// Updated: Added partial game verification, improved proof generation, and added SP1 explanation
import { Cell, PartialGameScore } from "./types";

// Calculate partial game score based on revealed cells and difficulty
export function calculatePartialScore(
  board: Cell[][],
  time: number,
  difficulty: string
): PartialGameScore {
  // Count revealed cells and total safe cells
  let revealedCells = 0;
  let totalSafeCells = 0;
  let totalMines = 0;
  
  for (let row = 0; row < board.length; row++) {
    for (let col = 0; col < board[0].length; col++) {
      if (board[row][col].isMine) {
        totalMines++;
      } else {
        totalSafeCells++;
        if (board[row][col].isRevealed) {
          revealedCells++;
        }
      }
    }
  }
  
  // Calculate percentage of completion
  const percentComplete = (revealedCells / totalSafeCells) * 100;
  
  // Calculate score based on percentage, time, and difficulty
  const difficultyMultiplier = 
    difficulty === "beginner" ? 1 :
    difficulty === "intermediate" ? 2.5 :
    difficulty === "expert" ? 5 : 1;
  
  // Base score calculation with progressive bonus
  // The more cells revealed, the higher the score per cell
  const progressiveBonus = Math.pow(percentComplete / 100, 1.5); // Exponential bonus for progress
  const timeBonus = Math.max(1, 100 / (time + 10)); // Faster times get better bonus
  
  // Final score calculation
  const score = Math.floor(
    revealedCells * difficultyMultiplier * progressiveBonus * timeBonus
  );
  
  return {
    score,
    percentComplete,
    cellsRevealed: revealedCells,
    totalSafeCells
  };
}

// SP1 proof generation for Minesweeper game
export async function generateGameProof(gameData: {
  board: Cell[][];
  time: number;
  difficulty: string;
  moves: string[];
  isPartial?: boolean;
}): Promise<string> {
  console.log("Generating SP1 proof for game data:", gameData);
  
  // In a real implementation, this would call the SP1 library to generate a ZK proof
  // The proof would verify:
  // 1. The board was generated with the correct number of mines
  // 2. All revealed cells follow valid game rules
  // 3. For complete games: the player revealed all non-mine cells (win condition)
  // 4. For partial games: the player revealed the claimed number of cells
  // 5. The time recorded is accurate
  
  // Calculate score based on whether this is a complete or partial game
  const isComplete = !gameData.isPartial;
  let score: number;
  let percentComplete: number = 100;
  let cellsRevealed: number = 0;
  let totalSafeCells: number = 0;
  
  if (isComplete) {
    // Complete game score calculation
    score = calculateScore(gameData.time, gameData.difficulty);
  } else {
    // Partial game score calculation
    const partialScore = calculatePartialScore(
      gameData.board,
      gameData.time,
      gameData.difficulty
    );
    score = partialScore.score;
    percentComplete = partialScore.percentComplete;
    cellsRevealed = partialScore.cellsRevealed;
    totalSafeCells = partialScore.totalSafeCells;
  }
  
  // For now, we'll simulate the proof generation with a delay
  return new Promise((resolve) => {
    setTimeout(() => {
      // Create a proof object that would normally be generated by SP1
      const mockProof = {
        gameId: Math.random().toString(36).substring(2, 15),
        timestamp: Date.now(),
        difficulty: gameData.difficulty,
        time: gameData.time,
        moveCount: gameData.moves.length,
        boardSize: {
          rows: gameData.board.length,
          cols: gameData.board[0].length
        },
        mineCount: countMines(gameData.board),
        score: score,
        isComplete: isComplete,
        percentComplete: percentComplete,
        cellsRevealed: cellsRevealed,
        totalSafeCells: totalSafeCells,
        verified: true,
        // This would be a real cryptographic signature in a real implementation
        signature: "0x" + Array(64).fill(0).map(() => Math.floor(Math.random() * 16).toString(16)).join('')
      };
      
      resolve(JSON.stringify(mockProof));
    }, 800); // Reduced delay to improve responsiveness
  });
}

// Helper function to count mines in a board
function countMines(board: Cell[][]): number {
  let count = 0;
  for (let row = 0; row < board.length; row++) {
    for (let col = 0; col < board[0].length; col++) {
      if (board[row][col].isMine) count++;
    }
  }
  return count;
}

// Calculate score based on time and difficulty
function calculateScore(time: number, difficulty: string): number {
  const difficultyMultiplier = 
    difficulty === "beginner" ? 1 :
    difficulty === "intermediate" ? 2.5 :
    difficulty === "expert" ? 5 : 1;
  
  // Base score calculation: faster times = higher scores
  // For example: 1000 * difficultyMultiplier / time
  const baseScore = Math.floor(1000 * difficultyMultiplier / time);
  
  return baseScore;
}

// Verify a game proof
export async function verifyGameProof(proof: string): Promise<{
  valid: boolean;
  score?: number;
  time?: number;
  difficulty?: string;
  gameId?: string;
  isComplete?: boolean;
  percentComplete?: number;
  cellsRevealed?: number;
  totalSafeCells?: number;
}> {
  console.log("Verifying SP1 proof:", proof);
  
  // In a real implementation, this would call the SP1 verifier
  // For now, we'll simulate verification with a delay
  return new Promise((resolve) => {
    setTimeout(() => {
      try {
        const proofData = JSON.parse(proof);
        if (proofData.verified) {
          resolve({
            valid: true,
            score: proofData.score,
            time: proofData.time,
            difficulty: proofData.difficulty,
            gameId: proofData.gameId,
            isComplete: proofData.isComplete,
            percentComplete: proofData.percentComplete,
            cellsRevealed: proofData.cellsRevealed,
            totalSafeCells: proofData.totalSafeCells
          });
        } else {
          resolve({ valid: false });
        }
      } catch (e) {
        resolve({ valid: false });
      }
    }, 500); // Reduced delay to improve responsiveness
  });
}

// WASM Module Interface
// This would be the interface to the Rust-compiled WASM module
export interface WasmInterface {
  // Core game functions
  generateBoard: (rows: number, cols: number, mines: number) => Uint8Array;
  revealCell: (board: Uint8Array, row: number, col: number) => { board: Uint8Array, hitMine: boolean };
  flagCell: (board: Uint8Array, row: number, col: number) => { board: Uint8Array, flagCount: number };
  checkWin: (board: Uint8Array, mines: number) => boolean;
  
  // SP1 proof generation
  generateProof: (
    board: Uint8Array, 
    moves: Uint8Array, 
    time: number, 
    difficulty: string
  ) => Uint8Array;
  
  // SP1 proof verification
  verifyProof: (proof: Uint8Array) => boolean;
}

// Placeholder for WASM module loading
export async function loadWasmModule(): Promise<WasmInterface | null> {
  // In a real implementation, this would load the Rust-compiled WASM module
  // For example:
  // const wasmModule = await import('@/wasm/minesweeper_bg.wasm');
  // return wasmModule as unknown as WasmInterface;
  
  console.log("WASM module would be loaded here");
  return null;
}